mapLocalesAndLanguage = {
    'cs': ['cs-cz'],
    'da': ['da-dk', 'da-dkk'],
    'de': ['de-at', 'de-chf', 'de-de'],
    'es': ['es-ar', 'es-arp', 'es-cl', 'es-co', 'es-cr', 'es-do', 'es-ec', 'es-es', 'es-in', 'es-mx', 'es-pa', 'es-pr', 'es-us', 'es-uy',],
    'fi': ['fi-fi'],
    'fr': ['fr-be', 'fr-ca', 'fr-chf', 'fr-fr', 'fr-lu'],
    'hu': ['hu-hu', 'hu-si'],
    'it': ['it-chf', 'it-it', 'it-si'],
    'ja': ['ja-jp'],
    'ko': ['ko-kr'],
    'nb': ['nn-no'],
    'nl': ['nl-be', 'nl-nl'],
    'pl': ['pl-pl'],
    'pt': ['pt-br', 'pt-pt'],
    'ru': ['ru-ru'],
    'sv': ['sv-se'],
    'th': ['th-th'],
    'tr': ['tr-cy', 'tr-tr'],
    'zh_hans': ['zh-cny'],
    'zh_hant': ['zh-hk', 'zh-tw'],
}